root 2020-04-22 20:17:06,972 <module> 24 :
 Driver%3D%7BODBC+Driver+17+for+SQL+Server%7D%3BServer%3Dtcp%3Apydoc-db.database.windows.net%2C1433%3BDatabase%3Dpydoc-db%3BUid%3Dhenry2833%3BPwd%3D%7BInfoip32%7D%3BEncrypt%3Dyes%3BTrustServerCertificate%3Dno%3BConnection+Timeout%3D30%3B

sqlalchemy.engine.base.Engine 2020-04-22 20:17:07,879 info 110 :
 SELECT CAST(SERVERPROPERTY('ProductVersion') AS VARCHAR)

sqlalchemy.engine.base.Engine 2020-04-22 20:17:07,879 info 110 :
 ()

sqlalchemy.engine.base.Engine 2020-04-22 20:17:07,966 info 110 :
 SELECT schema_name()

sqlalchemy.engine.base.Engine 2020-04-22 20:17:07,967 info 110 :
 ()

sqlalchemy.engine.base.Engine 2020-04-22 20:17:08,140 info 110 :
 SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1

sqlalchemy.engine.base.Engine 2020-04-22 20:17:08,140 info 110 :
 ()

sqlalchemy.engine.base.Engine 2020-04-22 20:17:08,221 info 110 :
 SELECT CAST('test unicode returns' AS NVARCHAR(60)) AS anon_1

sqlalchemy.engine.base.Engine 2020-04-22 20:17:08,222 info 110 :
 ()

sqlalchemy.engine.base.Engine 2020-04-22 20:17:08,396 info 110 :
 SELECT [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA], [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_NAME], [INFORMATION_SCHEMA].[COLUMNS].[IS_NULLABLE], [INFORMATION_SCHEMA].[COLUMNS].[DATA_TYPE], [INFORMATION_SCHEMA].[COLUMNS].[ORDINAL_POSITION], [INFORMATION_SCHEMA].[COLUMNS].[CHARACTER_MAXIMUM_LENGTH], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_PRECISION], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_SCALE], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_DEFAULT], [INFORMATION_SCHEMA].[COLUMNS].[COLLATION_NAME] 
FROM [INFORMATION_SCHEMA].[COLUMNS] 
WHERE [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))

sqlalchemy.engine.base.Engine 2020-04-22 20:17:08,397 info 110 :
 ('files', 'dbo')

sqlalchemy.engine.base.Engine 2020-04-22 20:17:08,566 info 110 :
 SELECT [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA], [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_NAME], [INFORMATION_SCHEMA].[COLUMNS].[IS_NULLABLE], [INFORMATION_SCHEMA].[COLUMNS].[DATA_TYPE], [INFORMATION_SCHEMA].[COLUMNS].[ORDINAL_POSITION], [INFORMATION_SCHEMA].[COLUMNS].[CHARACTER_MAXIMUM_LENGTH], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_PRECISION], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_SCALE], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_DEFAULT], [INFORMATION_SCHEMA].[COLUMNS].[COLLATION_NAME] 
FROM [INFORMATION_SCHEMA].[COLUMNS] 
WHERE [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))

sqlalchemy.engine.base.Engine 2020-04-22 20:17:08,566 info 110 :
 ('owner', 'dbo')

sqlalchemy.engine.base.Engine 2020-04-22 20:17:08,737 info 110 :
 SELECT [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA], [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_NAME], [INFORMATION_SCHEMA].[COLUMNS].[IS_NULLABLE], [INFORMATION_SCHEMA].[COLUMNS].[DATA_TYPE], [INFORMATION_SCHEMA].[COLUMNS].[ORDINAL_POSITION], [INFORMATION_SCHEMA].[COLUMNS].[CHARACTER_MAXIMUM_LENGTH], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_PRECISION], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_SCALE], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_DEFAULT], [INFORMATION_SCHEMA].[COLUMNS].[COLLATION_NAME] 
FROM [INFORMATION_SCHEMA].[COLUMNS] 
WHERE [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))

sqlalchemy.engine.base.Engine 2020-04-22 20:17:08,738 info 110 :
 ('dates', 'dbo')

sqlalchemy.engine.base.Engine 2020-04-22 20:17:08,930 info 110 :
 SELECT [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA], [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_NAME], [INFORMATION_SCHEMA].[COLUMNS].[IS_NULLABLE], [INFORMATION_SCHEMA].[COLUMNS].[DATA_TYPE], [INFORMATION_SCHEMA].[COLUMNS].[ORDINAL_POSITION], [INFORMATION_SCHEMA].[COLUMNS].[CHARACTER_MAXIMUM_LENGTH], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_PRECISION], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_SCALE], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_DEFAULT], [INFORMATION_SCHEMA].[COLUMNS].[COLLATION_NAME] 
FROM [INFORMATION_SCHEMA].[COLUMNS] 
WHERE [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))

sqlalchemy.engine.base.Engine 2020-04-22 20:17:08,930 info 110 :
 ('closure', 'dbo')

sqlalchemy.engine.base.Engine 2020-04-22 20:17:09,106 info 110 :
 SELECT [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA], [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_NAME], [INFORMATION_SCHEMA].[COLUMNS].[IS_NULLABLE], [INFORMATION_SCHEMA].[COLUMNS].[DATA_TYPE], [INFORMATION_SCHEMA].[COLUMNS].[ORDINAL_POSITION], [INFORMATION_SCHEMA].[COLUMNS].[CHARACTER_MAXIMUM_LENGTH], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_PRECISION], [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_SCALE], [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_DEFAULT], [INFORMATION_SCHEMA].[COLUMNS].[COLLATION_NAME] 
FROM [INFORMATION_SCHEMA].[COLUMNS] 
WHERE [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))

sqlalchemy.engine.base.Engine 2020-04-22 20:17:09,107 info 110 :
 ('filename', 'dbo')

__main__ 2020-04-22 20:17:09,361 start 76 :
 STARTING SQL testing2020-04-22 20:17:09.361537 /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/

sqlalchemy.engine.base.Engine 2020-04-22 20:17:10,117 info 110 :
 BEGIN (implicit)

sqlalchemy.engine.base.Engine 2020-04-22 20:17:10,120 info 110 :
 INSERT INTO owner (name) OUTPUT inserted.id VALUES (?)

sqlalchemy.engine.base.Engine 2020-04-22 20:17:10,121 info 110 :
 ('testing2020-04-04 22 Apr6-WhEo2isg',)

sqlalchemy.engine.base.Engine 2020-04-22 20:17:10,307 info 110 :
 COMMIT

sqlalchemy.engine.base.Engine 2020-04-22 20:17:10,619 info 110 :
 BEGIN (implicit)

sqlalchemy.engine.base.Engine 2020-04-22 20:17:10,621 info 110 :
 SELECT owner.id AS owner_id, owner.name AS owner_name 
FROM owner 
WHERE owner.id = ?

sqlalchemy.engine.base.Engine 2020-04-22 20:17:10,627 info 110 :
 (75,)

__main__ 2020-04-22 20:17:10,800 start 85 :
 Added owner row, name: testing2020-04-04 22 Apr6-WhEo2isg id: 75

__main__ 2020-04-22 20:17:10,806 start 93 :
 Finished loading pickles

__main__ 2020-04-22 20:17:10,808 start 109 :
 File: 1A7VHFEYQVj0bigcnBi3pn4NngcNXxH35Croy3zrdvLY

__main__ 2020-04-22 20:17:10,811 start 109 :
 File: 1WrjmluBbaNBS8u_WZmREl02_oMy2zv6Kcdte82zR5yk

__main__ 2020-04-22 20:17:10,813 start 109 :
 File: 1NO1CVAUsBSgghggdLH2X4YQ2XNaEkDmr7vK156pSCxk

sqlalchemy.engine.base.Engine 2020-04-22 20:17:10,817 info 110 :
 INSERT INTO files ([fileId], [lastModDate], [isFile]) VALUES (?, ?, ?)

sqlalchemy.engine.base.Engine 2020-04-22 20:17:10,817 info 110 :
 (('1A7VHFEYQVj0bigcnBi3pn4NngcNXxH35Croy3zrdvLY:22-20.3693936-WhEo2isg', datetime.datetime(2014, 12, 11, 16, 10, 21, 45000), 1), ('1WrjmluBbaNBS8u_WZmREl02_oMy2zv6Kcdte82zR5yk:22-20.3693936-WhEo2isg', datetime.datetime(2014, 12, 4, 17, 30, 58, 528000), 1), ('1NO1CVAUsBSgghggdLH2X4YQ2XNaEkDmr7vK156pSCxk:22-20.3693936-WhEo2isg', datetime.datetime(2014, 11, 21, 0, 2, 53, 318000, tzinfo=datetime.timezone.utc), 1))

__main__ 2020-04-22 20:17:11,171 start 125 :
 bulked save

sqlalchemy.engine.base.Engine 2020-04-22 20:17:11,177 info 110 :
 INSERT INTO files ([fileId], [lastModDate], parent_id, [isFile]) OUTPUT inserted.id VALUES (?, ?, ?, ?)

sqlalchemy.engine.base.Engine 2020-04-22 20:17:11,177 info 110 :
 ('1A7VHFEYQVj0bigcnBi3pn4NngcNXxH35Croy3zrdvLY:22-20.3693936-WhEo2isg', datetime.datetime(2014, 12, 11, 16, 10, 21, 45000), 75, 1)

sqlalchemy.engine.base.Engine 2020-04-22 20:17:11,357 info 110 :
 ROLLBACK

root 2020-04-22 20:17:11,459 handle_exception 74 :
 Custom Uncaught exception
Traceback (most recent call last):
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self.dialect.do_execute(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
pyodbc.IntegrityError: ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Violation of UNIQUE KEY constraint 'UQ__files__C2C6FFDDFAF40CED'. Cannot insert duplicate key in object 'dbo.files'. The duplicate key value is (1A7VHFEYQVj0bigcnBi3pn4NngcNXxH35Croy3zrdvLY:22-20.3693936-WhEo2isg). (2627) (SQLExecDirectW)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/henry/pydocs/processing/sql.py", line 249, in <module>
    start("testing" + datetime.now().__str__(), wpath)
  File "/home/henry/pydocs/processing/sql.py", line 147, in start
    sess.flush()
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1287, in _execute_context
    self._handle_dbapi_exception(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1481, in _handle_dbapi_exception
    util.raise_(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self.dialect.do_execute(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (pyodbc.IntegrityError) ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Violation of UNIQUE KEY constraint 'UQ__files__C2C6FFDDFAF40CED'. Cannot insert duplicate key in object 'dbo.files'. The duplicate key value is (1A7VHFEYQVj0bigcnBi3pn4NngcNXxH35Croy3zrdvLY:22-20.3693936-WhEo2isg). (2627) (SQLExecDirectW)")
[SQL: INSERT INTO files ([fileId], [lastModDate], parent_id, [isFile]) OUTPUT inserted.id VALUES (?, ?, ?, ?)]
[parameters: ('1A7VHFEYQVj0bigcnBi3pn4NngcNXxH35Croy3zrdvLY:22-20.3693936-WhEo2isg', datetime.datetime(2014, 12, 11, 16, 10, 21, 45000), 75, 1)]
(Background on this error at: http://sqlalche.me/e/gkpj)
root 2020-04-22 20:17:13,508 handle_exception 78 :
 exiting! from sshook

root 2020-04-22 20:17:13,509 handle_exception 80 :
 sending to default hook

