dsds.py:25,18:10:29:start:18:p3VzWg -- start
get_file:25,18:10:31:loadFiles:283:p3VzWg -- Start loadFiles, 527e4afc-4598-400f-8536-afa5324f0ba4 0B4Fujvv5MfqbVElBU01fZUxHcUk
requests:25,18:10:31:__call__:117:p3VzWg -- Making request: POST https://oauth2.googleapis.com/token
connecti:25,18:10:31:_new_conn:817:p3VzWg -- Starting new HTTPS connection (1): oauth2.googleapis.com
connecti:25,18:10:31:_make_request:393:p3VzWg -- https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
selector:25,18:10:31:__init__:59:p3VzWg -- Using selector: EpollSelector
test_uti:25,18:10:31:print_size:82:p3VzWg -- ---------------Memory usage: 92356 (kb)---------------0 mins since start
test_uti:25,18:10:31:print_size:88:p3VzWg -- /usr/lib/python3.8/tracemalloc.py:397: size=512 B (+512 B), count=3 (+3), average=171 B
test_uti:25,18:10:31:print_size:88:p3VzWg -- /usr/lib/python3.8/tracemalloc.py:534: size=472 B (+472 B), count=2 (+2), average=236 B
test_uti:25,18:10:31:print_size:88:p3VzWg -- /home/henry/pydocs/processing/datutils/test_utils.py:82: size=448 B (+448 B), count=1 (+1), average=448 B
test_uti:25,18:10:31:print_size:88:p3VzWg -- /home/henry/pydocs/processing/datutils/test_utils.py:86: size=424 B (+424 B), count=1 (+1), average=424 B
test_uti:25,18:10:31:print_size:88:p3VzWg -- /home/henry/pydocs/processing/datutils/test_utils.py:79: size=0 B (-424 B), count=0 (-1)
test_uti:25,18:10:31:print_size:88:p3VzWg -- /home/henry/pydocs/processing/datutils/test_utils.py:80: size=400 B (+400 B), count=1 (+1), average=400 B
test_uti:25,18:10:31:print_size:88:p3VzWg -- /usr/lib/python3.8/logging/__init__.py:330: size=48 B (+48 B), count=2 (+2), average=24 B
test_uti:25,18:10:31:print_size:88:p3VzWg -- /usr/lib/python3.8/tracemalloc.py:291: size=40 B (+40 B), count=1 (+1), average=40 B
test_uti:25,18:10:31:print_size:88:p3VzWg -- /usr/lib/python3.8/logging/__init__.py:329: size=24 B (+24 B), count=1 (+1), average=24 B
test_uti:25,18:10:31:print_size:88:p3VzWg -- /usr/lib/python3.8/logging/__init__.py:289: size=24 B (+24 B), count=1 (+1), average=24 B
test_uti:25,18:10:31:print_size:90:p3VzWg -- 

------------------------------


test_uti:25,18:10:31:print_size:93:p3VzWg -- /usr/lib/python3.8/tracemalloc.py:397: size=512 B, count=3, average=171 B
test_uti:25,18:10:31:print_size:93:p3VzWg -- /usr/lib/python3.8/tracemalloc.py:534: size=472 B, count=2, average=236 B
test_uti:25,18:10:31:print_size:93:p3VzWg -- /home/henry/pydocs/processing/datutils/test_utils.py:82: size=448 B, count=1, average=448 B
test_uti:25,18:10:31:print_size:93:p3VzWg -- /home/henry/pydocs/processing/datutils/test_utils.py:86: size=424 B, count=1, average=424 B
test_uti:25,18:10:31:print_size:93:p3VzWg -- /home/henry/pydocs/processing/datutils/test_utils.py:80: size=400 B, count=1, average=400 B
test_uti:25,18:10:31:print_size:93:p3VzWg -- /usr/lib/python3.8/logging/__init__.py:330: size=48 B, count=2, average=24 B
test_uti:25,18:10:31:print_size:93:p3VzWg -- /usr/lib/python3.8/tracemalloc.py:291: size=40 B, count=1, average=40 B
test_uti:25,18:10:31:print_size:93:p3VzWg -- /usr/lib/python3.8/logging/__init__.py:329: size=24 B, count=1, average=24 B
test_uti:25,18:10:31:print_size:93:p3VzWg -- /usr/lib/python3.8/logging/__init__.py:289: size=24 B, count=1, average=24 B
test_uti:25,18:10:31:print_size:93:p3VzWg -- /home/henry/pydocs/processing/datutils/test_utils.py:83: size=24 B, count=1, average=24 B
test_uti:25,18:10:31:print_size:100:p3VzWg -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
0/0 at 2020-04-25 18:10:31.598078
dumped: 0
get_file:25,18:10:31:getIdsRecursive:53:p3VzWg -- getIdsRecursive looping
get_file:25,18:10:32:getIdsRecursive:53:p3VzWg -- getIdsRecursive looping
get_file:25,18:10:33:getIdsRecursive:53:p3VzWg -- getIdsRecursive looping
get_file:25,18:10:33:getIdsRecursive:53:p3VzWg -- getIdsRecursive looping
get_file:25,18:10:34:getIdsRecursive:53:p3VzWg -- getIdsRecursive looping
get_file:25,18:10:34:getIdsRecursive:53:p3VzWg -- getIdsRecursive looping
get_file:25,18:10:35:getIdsRecursive:53:p3VzWg -- getIdsRecursive looping
get_file:25,18:10:35:getIdsRecursive:53:p3VzWg -- getIdsRecursive looping
get_file:25,18:10:35:getIdsRecursive:53:p3VzWg -- getIdsRecursive looping
get_file:25,18:10:36:getIdsRecursive:53:p3VzWg -- getIdsRecursive looping
get_file:25,18:10:36:getIdsRecursive:53:p3VzWg -- getIdsRecursive looping
test_uti:25,18:10:36:print_size:82:p3VzWg -- ---------------Memory usage: 92576 (kb)---------------0 mins since start
test_uti:25,18:10:36:print_size:88:p3VzWg -- /home/henry/pydocs/processing/datutils/test_utils.py:158: size=16.8 KiB (+16.8 KiB), count=196 (+196), average=88 B
test_uti:25,18:10:36:print_size:88:p3VzWg -- /home/henry/pydocs/processing/get_files.py:108: size=11.7 KiB (+11.7 KiB), count=278 (+278), average=43 B
test_uti:25,18:10:36:print_size:88:p3VzWg -- <frozen importlib._bootstrap_external>:580: size=10.9 KiB (+10.9 KiB), count=114 (+114), average=98 B
test_uti:25,18:10:36:print_size:88:p3VzWg -- /usr/lib/python3.8/abc.py:102: size=9568 B (+9568 B), count=99 (+99), average=97 B
test_uti:25,18:10:36:print_size:88:p3VzWg -- /home/henry/pydocs/processing/get_files.py:100: size=6070 B (+6070 B), count=82 (+82), average=74 B
test_uti:25,18:10:36:print_size:88:p3VzWg -- /usr/lib/python3.8/ssl.py:906: size=5500 B (+5500 B), count=87 (+87), average=63 B
test_uti:25,18:10:36:print_size:88:p3VzWg -- /usr/lib/python3.8/asyncio/events.py:81: size=5104 B (+5104 B), count=16 (+16), average=319 B
test_uti:25,18:10:36:print_size:88:p3VzWg -- /usr/lib/python3.8/concurrent/futures/thread.py:109: size=2999 B (+2999 B), count=12 (+12), average=250 B
test_uti:25,18:10:36:print_size:88:p3VzWg -- /usr/lib/python3.8/asyncio/base_events.py:702: size=2256 B (+2256 B), count=23 (+23), average=98 B
test_uti:25,18:10:36:print_size:88:p3VzWg -- /home/henry/pydocs/processing/get_files.py:103: size=2208 B (+2208 B), count=1 (+1), average=2208 B
test_uti:25,18:10:36:print_size:90:p3VzWg -- 

------------------------------


test_uti:25,18:10:36:print_size:93:p3VzWg -- /home/henry/pydocs/processing/datutils/test_utils.py:158: size=16.8 KiB, count=196, average=88 B
test_uti:25,18:10:36:print_size:93:p3VzWg -- /home/henry/pydocs/processing/get_files.py:108: size=11.7 KiB, count=278, average=43 B
test_uti:25,18:10:36:print_size:93:p3VzWg -- <frozen importlib._bootstrap_external>:580: size=10.9 KiB, count=114, average=98 B
test_uti:25,18:10:36:print_size:93:p3VzWg -- /usr/lib/python3.8/abc.py:102: size=9568 B, count=99, average=97 B
test_uti:25,18:10:36:print_size:93:p3VzWg -- /home/henry/pydocs/processing/get_files.py:100: size=6070 B, count=82, average=74 B
test_uti:25,18:10:36:print_size:93:p3VzWg -- /usr/lib/python3.8/ssl.py:906: size=5500 B, count=87, average=63 B
test_uti:25,18:10:36:print_size:93:p3VzWg -- /usr/lib/python3.8/asyncio/events.py:81: size=5104 B, count=16, average=319 B
test_uti:25,18:10:36:print_size:93:p3VzWg -- /usr/lib/python3.8/concurrent/futures/thread.py:109: size=2999 B, count=12, average=250 B
test_uti:25,18:10:36:print_size:93:p3VzWg -- /usr/lib/python3.8/asyncio/base_events.py:702: size=2256 B, count=23, average=98 B
test_uti:25,18:10:36:print_size:93:p3VzWg -- /home/henry/pydocs/processing/get_files.py:103: size=2208 B, count=1, average=2208 B
test_uti:25,18:10:36:print_size:100:p3VzWg -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
0/70 at 2020-04-25 18:10:36.668118
dumped: 0
get_file:25,18:10:37:getIdsRecursive:53:p3VzWg -- getIdsRecursive looping
test_uti:25,18:10:37:tryGetQueue:228:p3VzWg -- getIdswaiting 1 5
test_uti:25,18:10:41:print_size:82:p3VzWg -- ---------------Memory usage: 93316 (kb)---------------0 mins since start
test_uti:25,18:10:41:print_size:88:p3VzWg -- /home/henry/pydocs/processing/get_files.py:103: size=4632 B (+2424 B), count=1 (+0), average=4632 B
test_uti:25,18:10:41:print_size:88:p3VzWg -- /usr/lib/python3.8/tracemalloc.py:532: size=1456 B (+1400 B), count=26 (+25), average=56 B
test_uti:25,18:10:41:print_size:88:p3VzWg -- /home/henry/pydocs/processing/get_files.py:108: size=12.4 KiB (+736 B), count=294 (+16), average=43 B
test_uti:25,18:10:41:print_size:88:p3VzWg -- <string>:1: size=424 B (-640 B), count=5 (-8), average=85 B
test_uti:25,18:10:41:print_size:88:p3VzWg -- /home/henry/pydocs/processing/datutils/test_utils.py:229: size=568 B (+568 B), count=2 (+2), average=284 B
test_uti:25,18:10:41:print_size:88:p3VzWg -- <frozen importlib._bootstrap_external>:580: size=10.4 KiB (-512 B), count=111 (-3), average=96 B
test_uti:25,18:10:41:print_size:88:p3VzWg -- /usr/lib/python3.8/random.py:248: size=504 B (+504 B), count=1 (+1), average=504 B
test_uti:25,18:10:41:print_size:88:p3VzWg -- /usr/lib/python3.8/random.py:224: size=440 B (+440 B), count=1 (+1), average=440 B
test_uti:25,18:10:41:print_size:88:p3VzWg -- /usr/lib/python3.8/asyncio/locks.py:512: size=424 B (+424 B), count=1 (+1), average=424 B
test_uti:25,18:10:41:print_size:88:p3VzWg -- /usr/lib/python3.8/asyncio/base_events.py:702: size=1840 B (-416 B), count=17 (-6), average=108 B
test_uti:25,18:10:41:print_size:90:p3VzWg -- 

------------------------------


test_uti:25,18:10:41:print_size:93:p3VzWg -- /home/henry/pydocs/processing/datutils/test_utils.py:158: size=16.4 KiB, count=206, average=81 B
test_uti:25,18:10:41:print_size:93:p3VzWg -- /home/henry/pydocs/processing/get_files.py:108: size=12.4 KiB, count=294, average=43 B
test_uti:25,18:10:41:print_size:93:p3VzWg -- <frozen importlib._bootstrap_external>:580: size=10.4 KiB, count=111, average=96 B
test_uti:25,18:10:41:print_size:93:p3VzWg -- /usr/lib/python3.8/abc.py:102: size=9440 B, count=97, average=97 B
test_uti:25,18:10:41:print_size:93:p3VzWg -- /home/henry/pydocs/processing/get_files.py:100: size=6392 B, count=87, average=73 B
test_uti:25,18:10:41:print_size:93:p3VzWg -- /usr/lib/python3.8/ssl.py:906: size=5500 B, count=87, average=63 B
test_uti:25,18:10:41:print_size:93:p3VzWg -- /usr/lib/python3.8/asyncio/events.py:81: size=5144 B, count=17, average=303 B
test_uti:25,18:10:41:print_size:93:p3VzWg -- /home/henry/pydocs/processing/get_files.py:103: size=4632 B, count=1, average=4632 B
test_uti:25,18:10:41:print_size:93:p3VzWg -- /usr/lib/python3.8/concurrent/futures/thread.py:109: size=2999 B, count=12, average=250 B
test_uti:25,18:10:41:print_size:93:p3VzWg -- /home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/aiohttp/client.py:850: size=2000 B, count=7, average=286 B
test_uti:25,18:10:41:print_size:100:p3VzWg -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
0/74 at 2020-04-25 18:10:41.743449
dumped: 0
get_file:25,18:10:42:getRevision:166:p3VzWg -- getRevision looping
gdoc.py:25,18:10:42:async_init:24:p3VzWg -- async init called
gdoc.py:25,18:10:42:get_last_revision:53:p3VzWg -- last revision id 394
gdoc.py:25,18:10:42:async_init:33:p3VzWg -- after await 394
connecti:25,18:10:42:_new_conn:817:p3VzWg -- Starting new HTTPS connection (1): docs.google.com
connecti:25,18:10:43:_make_request:393:p3VzWg -- https://docs.google.com:443 "GET /document/d/1TYIOfz_uzybWgEeexs8iE64jcjt-AmUegOP6KORNaWQ/revisions/load?id=1TYIOfz_uzybWgEeexs8iE64jcjt-AmUegOP6KORNaWQ&start=1&end=394 HTTP/1.1" 200 None
gdoc.py:25,18:10:43:download_details:68:p3VzWg -- Cannot get revisions.json
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/gdoc.py", line 66, in download_details
    assert response.status == 200
AttributeError: 'Response' object has no attribute 'status'
get_file:25,18:10:43:getRevision:198:p3VzWg -- []
get_file:25,18:10:43:getRevision:201:p3VzWg -- google doc
get_file:25,18:10:43:getRevision:166:p3VzWg -- getRevision looping
gdoc.py:25,18:10:43:async_init:24:p3VzWg -- async init called
gdoc.py:25,18:10:43:get_last_revision:53:p3VzWg -- last revision id 1336
gdoc.py:25,18:10:43:async_init:33:p3VzWg -- after await 1336
connecti:25,18:10:43:_new_conn:817:p3VzWg -- Starting new HTTPS connection (1): docs.google.com
connecti:25,18:10:44:_make_request:393:p3VzWg -- https://docs.google.com:443 "GET /document/d/19Fu317bfo0V7yOIkfLvKtAU-UJYLf8d2Soy-jTvq1uc/revisions/load?id=19Fu317bfo0V7yOIkfLvKtAU-UJYLf8d2Soy-jTvq1uc&start=1&end=1336 HTTP/1.1" 200 None
gdoc.py:25,18:10:44:download_details:68:p3VzWg -- Cannot get revisions.json
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/gdoc.py", line 66, in download_details
    assert response.status == 200
AttributeError: 'Response' object has no attribute 'status'
get_file:25,18:10:44:getRevision:198:p3VzWg -- []
get_file:25,18:10:44:getRevision:201:p3VzWg -- google doc
get_file:25,18:10:44:getRevision:166:p3VzWg -- getRevision looping
gdoc.py:25,18:10:44:async_init:24:p3VzWg -- async init called
test_uti:25,18:10:44:tryGetQueue:228:p3VzWg -- getIdswaiting 2 5
gdoc.py:25,18:10:44:get_last_revision:53:p3VzWg -- last revision id 1946
gdoc.py:25,18:10:44:async_init:33:p3VzWg -- after await 1946
connecti:25,18:10:44:_new_conn:817:p3VzWg -- Starting new HTTPS connection (1): docs.google.com
connecti:25,18:10:44:_make_request:393:p3VzWg -- https://docs.google.com:443 "GET /document/d/1eXJKzIcZCM6pAdVLLrvEyIwQBDDrtm8dComeZ_W7uOI/revisions/load?id=1eXJKzIcZCM6pAdVLLrvEyIwQBDDrtm8dComeZ_W7uOI&start=1&end=1946 HTTP/1.1" 200 None
gdoc.py:25,18:10:44:download_details:68:p3VzWg -- Cannot get revisions.json
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/gdoc.py", line 66, in download_details
    assert response.status == 200
AttributeError: 'Response' object has no attribute 'status'
get_file:25,18:10:44:getRevision:198:p3VzWg -- []
get_file:25,18:10:44:getRevision:201:p3VzWg -- google doc
get_file:25,18:10:44:getRevision:166:p3VzWg -- getRevision looping
gdoc.py:25,18:10:44:async_init:24:p3VzWg -- async init called
gdoc.py:25,18:10:45:get_last_revision:53:p3VzWg -- last revision id 12
gdoc.py:25,18:10:45:async_init:33:p3VzWg -- after await 12
connecti:25,18:10:45:_new_conn:817:p3VzWg -- Starting new HTTPS connection (1): docs.google.com
connecti:25,18:10:45:_make_request:393:p3VzWg -- https://docs.google.com:443 "GET /document/d/1Ux4BA5BVJTcsGcTcGp8CtB85ahlWp0h83AGvrtAhnTg/revisions/load?id=1Ux4BA5BVJTcsGcTcGp8CtB85ahlWp0h83AGvrtAhnTg&start=1&end=12 HTTP/1.1" 200 None
gdoc.py:25,18:10:45:download_details:68:p3VzWg -- Cannot get revisions.json
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/gdoc.py", line 66, in download_details
    assert response.status == 200
AttributeError: 'Response' object has no attribute 'status'
get_file:25,18:10:45:getRevision:198:p3VzWg -- []
get_file:25,18:10:45:getRevision:201:p3VzWg -- google doc
get_file:25,18:10:45:getRevision:166:p3VzWg -- getRevision looping
get_file:25,18:10:45:getRevision:183:p3VzWg -- not google doc
get_file:25,18:10:46:getRevision:166:p3VzWg -- getRevision looping
gdoc.py:25,18:10:46:async_init:24:p3VzWg -- async init called
test_uti:25,18:10:46:print_size:82:p3VzWg -- ---------------Memory usage: 93696 (kb)---------------0 mins since start
test_uti:25,18:10:46:print_size:88:p3VzWg -- <frozen importlib._bootstrap_external>:580: size=78.4 KiB (+68.0 KiB), count=929 (+818), average=86 B
test_uti:25,18:10:46:print_size:88:p3VzWg -- /home/henry/pydocs/processing/datutils/test_utils.py:158: size=28.8 KiB (+12.4 KiB), count=348 (+142), average=85 B
test_uti:25,18:10:46:print_size:88:p3VzWg -- /usr/lib/python3.8/ssl.py:906: size=10.6 KiB (+5367 B), count=172 (+85), average=63 B
test_uti:25,18:10:46:print_size:88:p3VzWg -- /home/henry/pydocs/processing/get_files.py:148: size=4936 B (+4936 B), count=43 (+43), average=115 B
test_uti:25,18:10:46:print_size:88:p3VzWg -- <frozen importlib._bootstrap>:219: size=3523 B (+3523 B), count=40 (+40), average=88 B
test_uti:25,18:10:46:print_size:88:p3VzWg -- /usr/lib/python3.8/multiprocessing/connection.py:114: size=2444 B (+2444 B), count=9 (+9), average=272 B
test_uti:25,18:10:46:print_size:88:p3VzWg -- /home/henry/pydocs/processing/gdoc.py:51: size=2352 B (+2352 B), count=14 (+14), average=168 B
test_uti:25,18:10:46:print_size:88:p3VzWg -- /usr/lib/python3.8/multiprocessing/util.py:289: size=2344 B (+2344 B), count=2 (+2), average=1172 B
test_uti:25,18:10:46:print_size:88:p3VzWg -- /usr/lib/python3.8/multiprocessing/connection.py:727: size=2208 B (+2208 B), count=1 (+1), average=2208 B
test_uti:25,18:10:46:print_size:88:p3VzWg -- /usr/lib/python3.8/multiprocessing/connection.py:432: size=2058 B (+2058 B), count=10 (+10), average=206 B
test_uti:25,18:10:46:print_size:90:p3VzWg -- 

------------------------------


test_uti:25,18:10:46:print_size:93:p3VzWg -- <frozen importlib._bootstrap_external>:580: size=78.4 KiB, count=929, average=86 B
test_uti:25,18:10:46:print_size:93:p3VzWg -- /home/henry/pydocs/processing/datutils/test_utils.py:158: size=28.8 KiB, count=348, average=85 B
test_uti:25,18:10:46:print_size:93:p3VzWg -- /home/henry/pydocs/processing/get_files.py:108: size=11.6 KiB, count=274, average=43 B
test_uti:25,18:10:46:print_size:93:p3VzWg -- /usr/lib/python3.8/ssl.py:906: size=10.6 KiB, count=172, average=63 B
test_uti:25,18:10:46:print_size:93:p3VzWg -- /usr/lib/python3.8/abc.py:102: size=9314 B, count=95, average=98 B
test_uti:25,18:10:46:print_size:93:p3VzWg -- /home/henry/pydocs/processing/get_files.py:100: size=6392 B, count=87, average=73 B
test_uti:25,18:10:46:print_size:93:p3VzWg -- /usr/lib/python3.8/asyncio/events.py:81: size=5256 B, count=19, average=277 B
test_uti:25,18:10:46:print_size:93:p3VzWg -- /home/henry/pydocs/processing/get_files.py:148: size=4936 B, count=43, average=115 B
test_uti:25,18:10:46:print_size:93:p3VzWg -- /home/henry/pydocs/processing/get_files.py:103: size=4632 B, count=1, average=4632 B
test_uti:25,18:10:46:print_size:93:p3VzWg -- <frozen importlib._bootstrap>:219: size=3523 B, count=40, average=88 B
test_uti:25,18:10:46:print_size:100:p3VzWg -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
5/73 at 2020-04-25 18:10:46.829792
dumped: 0
gdoc.py:25,18:10:47:get_last_revision:53:p3VzWg -- last revision id 1394
gdoc.py:25,18:10:47:async_init:33:p3VzWg -- after await 1394
connecti:25,18:10:47:_new_conn:817:p3VzWg -- Starting new HTTPS connection (1): docs.google.com
connecti:25,18:10:47:_make_request:393:p3VzWg -- https://docs.google.com:443 "GET /document/d/1K6SwyWCOhW6dt906DjOIhJ-ZklpsooCdTyYHGfEZD2s/revisions/load?id=1K6SwyWCOhW6dt906DjOIhJ-ZklpsooCdTyYHGfEZD2s&start=1&end=1394 HTTP/1.1" 200 None
gdoc.py:25,18:10:47:download_details:68:p3VzWg -- Cannot get revisions.json
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/gdoc.py", line 66, in download_details
    assert response.status == 200
AttributeError: 'Response' object has no attribute 'status'
get_file:25,18:10:47:getRevision:198:p3VzWg -- []
get_file:25,18:10:47:getRevision:201:p3VzWg -- google doc
get_file:25,18:10:47:getRevision:166:p3VzWg -- getRevision looping
gdoc.py:25,18:10:47:async_init:24:p3VzWg -- async init called
gdoc.py:25,18:10:48:get_last_revision:53:p3VzWg -- last revision id 1782
gdoc.py:25,18:10:48:async_init:33:p3VzWg -- after await 1782
connecti:25,18:10:48:_new_conn:817:p3VzWg -- Starting new HTTPS connection (1): docs.google.com
connecti:25,18:10:48:_make_request:393:p3VzWg -- https://docs.google.com:443 "GET /document/d/1ak3AnxwEDfv_EkgRG7Q8U_eglT-eK2W3RtAJqlrtcQA/revisions/load?id=1ak3AnxwEDfv_EkgRG7Q8U_eglT-eK2W3RtAJqlrtcQA&start=1&end=1782 HTTP/1.1" 200 None
gdoc.py:25,18:10:48:download_details:68:p3VzWg -- Cannot get revisions.json
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/gdoc.py", line 66, in download_details
    assert response.status == 200
AttributeError: 'Response' object has no attribute 'status'
get_file:25,18:10:48:getRevision:198:p3VzWg -- []
get_file:25,18:10:48:getRevision:201:p3VzWg -- google doc
get_file:25,18:10:48:getRevision:166:p3VzWg -- getRevision looping
gdoc.py:25,18:10:48:async_init:24:p3VzWg -- async init called
gdoc.py:25,18:10:48:get_last_revision:53:p3VzWg -- last revision id 6533
gdoc.py:25,18:10:48:async_init:33:p3VzWg -- after await 6533
connecti:25,18:10:48:_new_conn:817:p3VzWg -- Starting new HTTPS connection (1): docs.google.com
connecti:25,18:10:49:_make_request:393:p3VzWg -- https://docs.google.com:443 "GET /document/d/1iTV26x-U2-nngY6gONVklMtrhdfI818IwLM682vpABA/revisions/load?id=1iTV26x-U2-nngY6gONVklMtrhdfI818IwLM682vpABA&start=1&end=6533 HTTP/1.1" 200 None
gdoc.py:25,18:10:49:download_details:68:p3VzWg -- Cannot get revisions.json
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/gdoc.py", line 66, in download_details
    assert response.status == 200
AttributeError: 'Response' object has no attribute 'status'
get_file:25,18:10:49:getRevision:198:p3VzWg -- []
get_file:25,18:10:49:getRevision:201:p3VzWg -- google doc
get_file:25,18:10:49:getRevision:166:p3VzWg -- getRevision looping
configlo:25,18:10:50:handle_exception:82:p3VzWg -- Custom Uncaught exception
Traceback (most recent call last):
  File "dsds.py", line 37, in <module>
    start()
  File "dsds.py", line 34, in start
    loadFiles(uid, workingPath, fileid, creds)
  File "/home/henry/pydocs/processing/get_files.py", line 308, in loadFiles
    loop.run_until_complete(asyncio.gather(startTask))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
configlo:25,18:10:50:sendmail:103:p3VzWg -- sending mail
configlo:25,18:10:50:handle_exception:86:p3VzWg -- exiting! from sshook
